### ISSUE TITLE
test: try Pocket Network nodes

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/brovider#163]
See Discord messages in #strategies

**Comment by ChaituVR** [comment]
Polygon node: 
- Not archive node (return missing trie node error)
- Works similar to current node (speed and payload limit)

Gnosis chain:
- Multicall response average time is high (took 3.3 secs where current node took 100ms)
- Works similar to current node (same payload limit)

ETH Mainnet:
- Works similar to current node (speed and payload limit)

Avax:
- Not working, I get error GS (avax-archival) load balancer not found 

BSC:
- Works similar to current node (faster response time but less payload limit accepts 1k addresses, current node accept 2.6k addresses)
